name: marginacion-en-educacion
channels:
  - conda-forge
dependencies:
  - pandas=1.0.*
  - altair=4.1*
  - bokeh=2.0.*
  - seaborn=0.10.*
  - matplotlib=3.2.*
  - pip=20.1.*
  - pip:
    - xlrd==1.2.*  